export const POST_EATEN_PRODUCT = 'POST_EATEN_PRODUCT';

export const POST_EATEN_PRODUCT_SUCCEEDED = 'POST_EATEN_PRODUCT_SUCCEEDED';

export const GET_DAY_INFO = 'GET_DAY_INFO';

export const GET_DAY_INFO_SUCCEEDED = 'GET_DAY_INFO_SUCCEEDED';
