export const REGISTER_USER = 'REGISTER_USER';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCEEDED = 'LOGIN_USER_SUCCEEDED';
export const LOGOUT_USER = 'LOGOUT_USER';
export const GET_USER_INFO = 'GET_USER_INFO';